### ISSUE TITLE
Can't get user details

### ISSUE THREAD

**Issue by TheMiao** [microsoftgraph/msgraph-training-aspnetmvcapp#11]
The project is working fine before "Get user details"
https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp/blob/master/Lab.md#get-user-details

After implement sample code after "get user details". It does retrieved access token, however it won't direct to the correct page. It will back to the index with login showing on the top right corner

**Comment by jasonjoh** [comment]
Sorry to hear that. Have you run it in the debugger with breakpoints to see if anything is failing?

**Comment by TheMiao** [comment]
@jasonjoh  Hey Jason, 
Thanks for follow up.

It works fine today. I guess the reason is I haven't clean the session and cookies in browser before run the project, and it is the reason I've constantly retrieve false value in Request.IsAuthenticated.
