### ISSUE TITLE
Session null

### ISSUE THREAD

**Issue by hannespreishuber** [microsoftgraph/msgraph-training-aspnetmvcapp#13]
I try do adopt the code to ASP.NET Webforms 
run in error on authentication, reason is Session is null (nothing). Here in sample ctx.session. The same code as C# in this MVC sample works. Any idea where to investigate?

        Private Async Function OnAuthorizationCodeReceivedAsync(ByVal notification As AuthorizationCodeReceivedNotification) As Task
        Dim signedInUserId As String = notification.AuthenticationTicket.Identity.FindFirst(ClaimTypes.NameIdentifier).Value

        Dim ctx = TryCast(notification.OwinContext.Environment("System.Web.HttpContextBase"), HttpContextBase)
        Dim tokenStore As SessionTokenStore = New SessionTokenStore(signedInUserId, ctx)`

**Comment by hannespreishuber** [comment]
several tries later- still open issue
Visual Studio create Web Project (also C#) select autorization (Company …) insert our Domain 
insert in startupauth.cs

           AuthorizationCodeReceived = (context) =>
                        {
                            var code = context.Code;
                            var ctx = context.OwinContext.Environment["System.Web.HttpContextBase"] as HttpContextBase;

and still ctx.session is null

**Comment by jasonjoh** [comment]
I suspect it might have to do with this:

> select autorization (Company …)

Are you referring to this dialog?

![image](https://user-images.githubusercontent.com/8966342/49026159-22a78a00-f16b-11e8-91c8-93b0f674b433.png)

If so, which option exactly did you choose?

**Comment by hannespreishuber** [comment]
"work or school"

**Comment by jasonjoh** [comment]
Very interesting. I see this behavior too. There must be some difference between using "No Authentication" (which is what this training does) and the "Work or School" option. It looks like "Work or School" adds some of the OWIN initialization that we add manually in the training, but I also see some web.config entries that are different. That might be what's causing the lack of session during auth.

Have you tried creating a web forms project with the "No Authentication" choice?

**Comment by hannespreishuber** [comment]
did a complete web.config switch, copied all assemblies, compared code- I do not find the issue

**Comment by jasonjoh** [comment]
Yeah I'm not really sure what to tell you here. I see you opened https://github.com/aspnet/AspNetKatana/issues/243 in the OWIN repository, which is definitely a better place to ask about this behavior. It must be something about how web forms handles session (vs MVC). I'm going to close this issue here.
