### ISSUE TITLE
Readme.md Appears to be out of date

### ISSUE THREAD

**Issue by BillStrait** [microsoftgraph/msgraph-training-aspnetmvcapp#20]
The readme.md that is downloaded with the project references steps that I believe are handled automatically by https://developer.microsoft.com/en-us/graph/quick-start. Maybe add a note that the readme does not apply to versions of the code from that source?

**Comment by andrewconnell** [comment]
Can you clarify exactly what you're referring to?

**Comment by BillStrait** [comment]
As of right now the content appears to be refreshed (for example, registration now points to portal.azure.com instead of apps.dev.microsoft.com), and there are different labs and videos referenced than the one I was working off of. I think you've already addressed this. Thanks!
