### ISSUE TITLE
Calendar data for multiple users

### ISSUE THREAD

**Issue by medida** [microsoftgraph/msgraph-training-aspnetmvcapp#26]
I have built the example and thats all fantastic....

But i need to expand the idea to allow users to login and then their calendar data to be displayed along with all other users who have logged in.

This is to create a common calendar across multiple accounts. 

So - could this be updated so the TOKEN which are stored in a DB are looped through to then call the GetEventsAsync....
But would there be limit to number of calls which can be made to the GRAPH API service???

thanks

**Comment by jasonjoh** [comment]
Yes you could do that, or you could use an [app-only token](https://docs.microsoft.com/graph/auth-v2-service) with an org admin's consent so you could access all calendars in your organization. That's beyond the scope of this training though.

Information on throttling is here: https://docs.microsoft.com/graph/throttling

**Comment by medida** [comment]
thanks - At this stage i do not know if all USERS will be from the same organisation - so wanted to keep it separated if i could.... the project brief at this stage is still very loose.
