### ISSUE TITLE
Error: Too many redirects.

### ISSUE THREAD

**Issue by RafaelL2409** [microsoftgraph/msgraph-training-aspnetmvcapp#27]
I used your example to authenticate a local web app in Visual Studio 2017 with Azure and it works fine, I integrated your code in my application, however, when I try to move the app to a Azure Web App, I made the changes in the App registration (Azure) and in the privatesetting.config file, to use the Azure URL, but it send me a error: ERR_TOO_MANY_REDIRECTS.   Of course I delete the cookies but it does not work. I can access some pages of the site in Azure withour problems, but when I tra to used the authentication id does not work. Please I need help to solve this issue.  I added the images where I changed to Azure URL, in fact I added the "...Home/Index" to be sure it goes to the root page but it does not work.
![image](https://user-images.githubusercontent.com/51338609/58828120-511a8c00-860a-11e9-8cf1-d3ba67d2cdba.png)

![image](https://user-images.githubusercontent.com/51338609/58828182-7effd080-860a-11e9-93e7-22a811e5b531.png)
![image](https://user-images.githubusercontent.com/51338609/58828216-8e7f1980-860a-11e9-96af-d70744bdb401.png)

**Comment by jasonjoh** [comment]
I would suggest debugging it in Azure, setting breakpoints on `OnAuthenticationFailedAsync` and `OnAuthorizationCodeReceivedAsync` to see what's happening. Also, if you're doing any checks for authentication in your `Index` function in `HomeController`, you might want to debug that to see if there's something unexpected going on.

**Comment by RafaelL2409** [comment]
I followed  your recomendation, however I do not see anything, in fact even when I set the debuggers stops, It does not arrives there,  it sends the same error: ERR_TOO_MANY_REDIRECTS.
The code works fine in my local enviroment, but when I try to run that in Azure I got that error.  Please check the images I am attaching to see if you have any other idea.

![image](https://user-images.githubusercontent.com/51338609/58893654-2dad1b00-86b6-11e9-8618-1f74e910b798.png)

![image](https://user-images.githubusercontent.com/51338609/58893677-356cbf80-86b6-11e9-9708-2bfecbf882dc.png)

![image](https://user-images.githubusercontent.com/51338609/58893711-43badb80-86b6-11e9-8a04-7f2d096f8ef8.png)

![image](https://user-images.githubusercontent.com/51338609/58893727-4c131680-86b6-11e9-8251-1283e0416530.png)

![image](https://user-images.githubusercontent.com/51338609/58893743-546b5180-86b6-11e9-8002-8df6ab3d4e43.png)

![image](https://user-images.githubusercontent.com/51338609/58893772-60571380-86b6-11e9-83f8-2e4c058c504b.png)

![image](https://user-images.githubusercontent.com/51338609/58893787-677e2180-86b6-11e9-8643-b47c0bb1257e.png)

![image](https://user-images.githubusercontent.com/51338609/58893810-71078980-86b6-11e9-9da3-a372bd7ebb7f.png)

**Comment by jasonjoh** [comment]
It's possible you're not hitting breakpoints due to Release build optimization, you might want to publish a debug build and see if that helps.

Also can you share your code for your Index function in HomeController? From your logs it looks like your app is redirecting to itself multiple times.

**Comment by RafaelL2409** [comment]
Here is the way the publish is configurated, if you have any suggestion it is welcome.

![image](https://user-images.githubusercontent.com/51338609/58897229-73211680-86bd-11e9-9d7f-efa28883b401.png)

![image](https://user-images.githubusercontent.com/51338609/58897237-77e5ca80-86bd-11e9-8220-8069a4e833f5.png)


This the code for Home/Index:  In my local enviroment works fine, the problem is when I use Azure. If you need more code I can send you without problem, however it is similar to the example you publish here. I attached the code for some classes and chenged the file extension to load here.



[GraphHelper.txt](https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp/files/3253549/GraphHelper.txt)
[HomeController.txt](https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp/files/3253550/HomeController.txt)
[SessionTokenStore.txt](https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp/files/3253551/SessionTokenStore.txt)
[Startup.Auth.txt](https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp/files/3253552/Startup.Auth.txt)

 


        public async  Task<ActionResult> Index()
        {
            try
            {
                ViewBag.UsuX = TempData["usuX"].ToString();
                TempData["usuX"]= TempData["usuX"].ToString();
                var grupos = await GraphHelper.GetGruposPerteneceAsync();
                int gAdmin = grupos.ToList().FindIndex(a => a.DisplayName == "G-SIGEMA");
                ViewBag.GAdmin = gAdmin;
                TempData["Admin"] = 0;
               
                List<string> gruposF = new List<string>();
                
                foreach (Microsoft.Graph.Group c in grupos)
                {
                    gruposF.Add(c.DisplayName.ToString());

                    var aG = from a in db.GruposApp
                             where a.Grupo == c.DisplayName.ToString().Trim()
                             select a.Admin;

                  

                    if (aG.FirstOrDefault() ==  1)
                    { 
                        TempData["Admin"] = 1;
                       // adminUsu = 1;
                    }

                }

                ViewBag.GruposAcceso = gruposF;
                TempData["GruposA"] = gruposF;
               // GruposU = gruposF;

            }
            catch
            {
                ViewBag.UsuX = "";
            }

            return View();
        }

**Comment by jasonjoh** [comment]
Yeah I'm not really sure what's going on there as we're getting a bit out of my depth :). I suspect it's an Azure problem rather than a code problem related to HTTPS. One question I have is, when you initially browse to the app, do you type in `eigosigema.azurewebsites.net`, or do you specify the https like `https://eigosigema.azurewebsites.net`?

You might need to contact Azure support through the portal.

**Comment by RafaelL2409** [comment]
Yes I specify: https://eigosigema.azurewebsites.net


![image](https://user-images.githubusercontent.com/51338609/58900980-d0b96100-86c5-11e9-9bbf-fe2249cc19b6.png)


Do you think I have to check sometyhing in Azure Portal?, anything with protocols?, any configuration? Because if for example I call other controller without authentication process, it works, you can see the weppage.
https://eigosigema.azurewebsites.net/Sitios/IndexP

![image](https://user-images.githubusercontent.com/51338609/58901317-9603f880-86c6-11e9-97d6-9f882775f8ab.png)

**Comment by jasonjoh** [comment]
I'm not really sure. I just did a quick test publishing this sample to Azure and I don't reproduce the problem. What do your SSL settings look like in Azure?

**Comment by RafaelL2409** [comment]
This is the information of SSL

![image](https://user-images.githubusercontent.com/51338609/58914701-d2465180-86e4-11e9-8cd6-0eaffd1abfe5.png)

However, I was working with the Azure Admin of my company, we create another App service and it works, I am comparing both App Service to see which was the problem. Do you have any other recommendation o issue I should check to see it I can solved the problem with the original AppService

**Comment by jasonjoh** [comment]
Sorry I'm just not an expert on the Azure side. Your SSL settings look fine. My test app service had HTTPS Only set to Off (that was the default). I switched it to On and still do not reproduce. I wonder if there was some provisioning error that happened with your original app service that caused this issue.

I'd probably do what you're already doing, comparing the two app services to see if there's anything that might be different.

**Comment by sawpresto** [comment]
Hi @jasonjoh, I recently deployed this to App Service and I was able to reproduce @RafaelL2409's issue - it looks like when you don't have App Service Authentication enabled on the app, then there aren't issues with redirects. However, once you add App Service Auth onto the app (login with AAD), then when trying to go to the website, the redirect issue happens. Do you know if there's any workaround for how to have both App Service auth and login enabled?

**Comment by jasonjoh** [comment]
Hmm, yeah this looks like it's intended to do all the auth for you. I'm not familiar enough with the Azure feature to know exactly, but I suspect if you use App Service Authentication you don't need to write all of the auth code in this sample. Not sure on the particulars of getting a Graph-compatible access token using this feature.

**Comment by sawpresto** [comment]
Agreed! Not sure if that's what he ran into but definitely helped clear it up for me. Thanks!
