### ISSUE TITLE
MSAL.NET 4.0 update breaks this tutorial

### ISSUE THREAD

**Issue by dcmesh** [microsoftgraph/msgraph-training-aspnetmvcapp#32]
I had used this tutorial as a basis for a web app that I am working on, running on C# with all packages up-to-date as of this post. However, I needed access to the GetSchedule() method for Microsoft Graph, and thus needed to switch to MSAL 4.0 in order to do so. This switch creates an issue with the SessionsTokenStore.cs file. 

Line 57 marks the first of two methods that are causing the problem:
`private void Load()`
`{`
 `    sessionLock.EnterReadLock();`
 `    tokenCache.DeserializeMsalV3((byte[])httpContext.Session[cacheId]);`
   `  sessionLock.ExitReadLock();`
`}`

`private void Persist()`
`{`
     `sessionLock.EnterReadLock();`
     `httpContext.Session[cacheId] = tockenCache.SerializeMsalV3();`
   `  sessionLock.ExitReadLock();
`}`

These two methods now give the following errors:
`ITokenCache.DeserializeMsalV3(byte[], bool) is now obsolete. Use ITokenCacheSerializer.DeserializeMsalV3 on the TokenCacheNotificationArgs in the cache callback.`

and 

`ITokenCache.SerializeMsalV3() is obsolete. Use ITokenCacheSerializer.SerializerMsalV3 on the TokenCacheNotificationArgs in the cache callback. `

From what I've seen, these are the only things impacted by the MSAL 4.0 update. How should I go about fixing this?

**Comment by jasonjoh** [comment]
I've updated the project to use MSAL 4.0 in the vs-2019 branch: https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp/tree/vs-2019. This will get merged into master in the near future.

**Comment by dcmesh** [comment]
Thank you! That fixed the issue.
