### ISSUE TITLE
Need admin approval

### ISSUE THREAD

**Issue by whenslunch** [microsoftgraph/msgraph-training-aspnetmvcapp#39]
Hi, thanks for the tutorial.
I followed all instructions but after I logged in to the app, I got a message saying:
"Need admin approval
My ASP.NET App
My ASP.NET App needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.
Have an admin account? Sign in with that account 
Return to the application without granting consent"
(And yes, I am a Microsoft employee.)
What do I need to do, at this point?
Thanks again.

**Comment by hanifmulani** [comment]
You will require an ‘Admin Consent’ grant for your application registered in Azure AD. Your application might be using endpoint which is admin consented,e.g. like Microsoft Graphs 'User.Read'.

Microsoft identity platform endpoint checks for a consent. If the user has not consented to the requested permissions then it will display a consent popup.

More information - https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-admin-consent
https://docs.microsoft.com/en-us/azure/active-directory/develop/application-consent-experience

**Comment by jasonjoh** [comment]
Microsoft's IT has disabled our ability to consent to third-party apps for a lot of permission scopes, including Calendars.Read (which is what this sample uses). That's why you're seeing that prompt. Your best bet is to use a test tenant to test the APIs.
