### ISSUE TITLE
changing to single tennant

### ISSUE THREAD

**Issue by d1och** [microsoftgraph/msgraph-training-aspnetmvcapp#54]
i have my app registration as a single tennant ie only from the same organisation.

i have changed the authority to this
Authority = "https://login.microsoftonline.com/[mytennantid]/v2.0"

and i still get this error message even though i have not used common anywhere in the app.

the error gets thrown here at this line in the startup file:
var result = await idClient.AcquireTokenByAuthorizationCode(
                    scopes, notification.Code).ExecuteAsync()

error received:

ex.Message = "AADSTS50194: Application '[myappid]'(name) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint o...

**Comment by jasonjoh** [comment]
Check where you create your MSAL client. The builder has a `WithAuthority` function that you can use to set the authority, and a `WithTenantId` function to provide your tenant ID. Do something like:

```
var idClient = ConfidentialClientApplicationBuilder.Create(appId)
                .WithRedirectUri(redirectUri)
                .WithClientSecret(appSecret)
                .WithAuthority(AadAuthorityAudience.AzureAdMyOrg)
                .WithTenantId("")
                .Build();
```

**Comment by d1och** [comment]
ok thats great, that solved it.
